### ISSUE TITLE
出现了一个问题

### ISSUE THREAD

**Issue by kkshell** [Wensibob/Wensibob.github.io#5]
我刚刚使用了畅言的评论换掉了多说的，然后可以通过hexo -g d来提交到github上去，但是我修改了_config.yml的title和subtitle之后hexo -g d就出现错误

123@JJ-SHELL-PC MINGW64 ~/blog
$ hexo g -d
FATAL can not read a block mapping entry; a multiline key may not be an implicit key at line 8, column 12:
    description:
               ^
Error
    at generateError (C:\Users\123\blog\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (C:\Users\123\blog\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at readBlockMapping (C:\Users\123\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1045:9)
    at composeNode (C:\Users\123\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1331:12)
    at readDocument (C:\Users\123\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1493:3)
    at loadDocuments (C:\Users\123\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1549:5)
    at Object.load (C:\Users\123\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1566:19)
    at Hexo.yamlHelper (C:\Users\123\blog\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (C:\Users\123\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\123\blog\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\123\blog\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (C:\Users\123\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\123\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\123\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\123\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\123\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\123\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\123\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\123\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by kkshell** [comment]
弄好了   空格的问题。。
